version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backend/bot_config_cache.json:/app/bot_config_cache.json
      - ./backend/binance_api_keys.json:/app/binance_api_keys.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
